spring:
  application:
    name: FinTrack

  datasource:
    url: jdbc:postgresql://localhost:5432/fintrack
    username: postgres
    password: p@ssw0rd123
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate # flyway create tables instead of hibernate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true # auto create flyway_schema_history if not exist
    locations: classpath:db/migration