spring:
  application:
    name: FinTrack

  datasource:
    # Try to get DB_HOST from Env (Docker), if not found, use 'localhost'
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:fintrack_db}
    # Logic: Read from Environment Variables (set in .env or Docker)
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate # flyway create tables instead of hibernate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true # auto create flyway_schema_history if not exist
    locations: classpath:db/migration

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/fintrack-realm}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8081/realms/fintrack-realm/protocol/openid-connect/certs}